15:17:42,120 logger WARNING Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Arick', id=130414078, last_name='Vigas', type=<ChatType.PRIVATE>, username='ArickVigas'), date=datetime.datetime(2023, 2, 9, 13, 17, 41, tzinfo=<UTC>), delete_chat_photo=False, entities=(MessageEntity(length=6, offset=0, type=<MessageEntityType.BOT_COMMAND>),), from_user=User(first_name='Arick', id=130414078, is_bot=False, is_premium=True, language_code='en', last_name='Vigas', username='ArickVigas'), group_chat_created=False, message_id=902, supergroup_chat_created=False, text='/start'), update_id=441137217)" caused error "'username'"
15:20:52,948 logger WARNING Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Arick', id=130414078, last_name='Vigas', type=<ChatType.PRIVATE>, username='ArickVigas'), date=datetime.datetime(2023, 2, 9, 13, 20, 52, tzinfo=<UTC>), delete_chat_photo=False, entities=(MessageEntity(length=6, offset=0, type=<MessageEntityType.BOT_COMMAND>),), from_user=User(first_name='Arick', id=130414078, is_bot=False, is_premium=True, language_code='en', last_name='Vigas', username='ArickVigas'), group_chat_created=False, message_id=907, supergroup_chat_created=False, text='/start'), update_id=441137220)" caused error "'DocumentReference' object has no attribute 'to_dict'"
15:22:17,895 logger WARNING Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Arick', id=130414078, last_name='Vigas', type=<ChatType.PRIVATE>, username='ArickVigas'), date=datetime.datetime(2023, 2, 9, 13, 22, 17, tzinfo=<UTC>), delete_chat_photo=False, entities=(MessageEntity(length=6, offset=0, type=<MessageEntityType.BOT_COMMAND>),), from_user=User(first_name='Arick', id=130414078, is_bot=False, is_premium=True, language_code='en', last_name='Vigas', username='ArickVigas'), group_chat_created=False, message_id=908, supergroup_chat_created=False, text='/start'), update_id=441137221)" caused error "'DocumentReference' object has no attribute 'to_dict'"
15:23:51,339 logger WARNING Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Arick', id=130414078, last_name='Vigas', type=<ChatType.PRIVATE>, username='ArickVigas'), date=datetime.datetime(2023, 2, 9, 13, 23, 51, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Arick', id=130414078, is_bot=False, is_premium=True, language_code='en', last_name='Vigas', username='ArickVigas'), group_chat_created=False, message_id=911, supergroup_chat_created=False, text='Привіт)'), update_id=441137223)" caused error "'list' object has no attribute 'get'"
15:26:55,844 logger WARNING Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Arick', id=130414078, last_name='Vigas', type=<ChatType.PRIVATE>, username='ArickVigas'), date=datetime.datetime(2023, 2, 9, 13, 26, 55, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Arick', id=130414078, is_bot=False, is_premium=True, language_code='en', last_name='Vigas', username='ArickVigas'), group_chat_created=False, message_id=912, supergroup_chat_created=False, text='Привіт)'), update_id=441137224)" caused error "400 The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/chatgptbot-af047/firestore/indexes?create_composite=ClZwcm9qZWN0cy9jaGF0Z3B0Ym90LWFmMDQ3L2RhdGFiYXNlcy8oZGVmYXVsdCkvY29sbGVjdGlvbkdyb3Vwcy9jb252ZXJzYXRpb25zL2luZGV4ZXMvXxABGgsKB3VzZXJfaWQQARoVChFjcmVhdGVkX3RpbWVzdGFtcBACGgwKCF9fbmFtZV9fEAI"
15:28:36,103 logger WARNING Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Arick', id=130414078, last_name='Vigas', type=<ChatType.PRIVATE>, username='ArickVigas'), date=datetime.datetime(2023, 2, 9, 13, 28, 35, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Arick', id=130414078, is_bot=False, is_premium=True, language_code='en', last_name='Vigas', username='ArickVigas'), group_chat_created=False, message_id=913, supergroup_chat_created=False, text='Привіт)'), update_id=441137225)" caused error "coroutine raised StopIteration"
15:29:13,177 logger WARNING Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Arick', id=130414078, last_name='Vigas', type=<ChatType.PRIVATE>, username='ArickVigas'), date=datetime.datetime(2023, 2, 9, 13, 29, 12, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Arick', id=130414078, is_bot=False, is_premium=True, language_code='en', last_name='Vigas', username='ArickVigas'), group_chat_created=False, message_id=914, supergroup_chat_created=False, text='Привіт)'), update_id=441137226)" caused error "coroutine raised StopIteration"
15:34:06,930 logger WARNING Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Arick', id=130414078, last_name='Vigas', type=<ChatType.PRIVATE>, username='ArickVigas'), date=datetime.datetime(2023, 2, 9, 13, 34, 7, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Arick', id=130414078, is_bot=False, is_premium=True, language_code='en', last_name='Vigas', username='ArickVigas'), group_chat_created=False, message_id=915, supergroup_chat_created=False, text='Привіт)'), update_id=441137227)" caused error "'generator' object has no attribute 'count'"
15:36:48,913 logger WARNING Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Arick', id=130414078, last_name='Vigas', type=<ChatType.PRIVATE>, username='ArickVigas'), date=datetime.datetime(2023, 2, 9, 13, 36, 48, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Arick', id=130414078, is_bot=False, is_premium=True, language_code='en', last_name='Vigas', username='ArickVigas'), group_chat_created=False, message_id=916, supergroup_chat_created=False, text='Привіт)'), update_id=441137228)" caused error "'CollectionReference' object has no attribute 'update'"
15:38:28,321 logger WARNING Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Arick', id=130414078, last_name='Vigas', type=<ChatType.PRIVATE>, username='ArickVigas'), date=datetime.datetime(2023, 2, 9, 13, 38, 27, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Arick', id=130414078, is_bot=False, is_premium=True, language_code='en', last_name='Vigas', username='ArickVigas'), group_chat_created=False, message_id=917, supergroup_chat_created=False, text='Привіт)'), update_id=441137229)" caused error "'DocumentSnapshot' object has no attribute 'update'"
15:41:09,417 logger WARNING Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Arick', id=130414078, last_name='Vigas', type=<ChatType.PRIVATE>, username='ArickVigas'), date=datetime.datetime(2023, 2, 9, 13, 41, 8, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Arick', id=130414078, is_bot=False, is_premium=True, language_code='en', last_name='Vigas', username='ArickVigas'), group_chat_created=False, message_id=918, supergroup_chat_created=False, text='Хей'), update_id=441137230)" caused error "'DocumentSnapshot' object has no attribute 'update'"
15:41:32,295 logger WARNING Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Arick', id=130414078, last_name='Vigas', type=<ChatType.PRIVATE>, username='ArickVigas'), date=datetime.datetime(2023, 2, 9, 13, 41, 31, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Arick', id=130414078, is_bot=False, is_premium=True, language_code='en', last_name='Vigas', username='ArickVigas'), group_chat_created=False, message_id=919, supergroup_chat_created=False, text='Хей'), update_id=441137231)" caused error "get() missing 1 required positional argument: 'field_path'"
15:41:38,685 logger WARNING Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Arick', id=130414078, last_name='Vigas', type=<ChatType.PRIVATE>, username='ArickVigas'), date=datetime.datetime(2023, 2, 9, 13, 41, 38, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Arick', id=130414078, is_bot=False, is_premium=True, language_code='en', last_name='Vigas', username='ArickVigas'), group_chat_created=False, message_id=920, supergroup_chat_created=False, text='Хей'), update_id=441137232)" caused error "get() missing 1 required positional argument: 'field_path'"
15:44:52,629 logger WARNING Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Arick', id=130414078, last_name='Vigas', type=<ChatType.PRIVATE>, username='ArickVigas'), date=datetime.datetime(2023, 2, 9, 13, 44, 51, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Arick', id=130414078, is_bot=False, is_premium=True, language_code='en', last_name='Vigas', username='ArickVigas'), group_chat_created=False, message_id=921, supergroup_chat_created=False, text='Хей'), update_id=441137233)" caused error "'DocumentSnapshot' object has no attribute 'update'"
15:51:51,314 logger WARNING Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Arick', id=130414078, last_name='Vigas', type=<ChatType.PRIVATE>, username='ArickVigas'), date=datetime.datetime(2023, 2, 9, 13, 51, 50, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Arick', id=130414078, is_bot=False, is_premium=True, language_code='en', last_name='Vigas', username='ArickVigas'), group_chat_created=False, message_id=922, supergroup_chat_created=False, text='Хей'), update_id=441137234)" caused error "('Cannot convert to a Firestore Value', Sentinel: Value used to set a document field to the server timestamp., 'Invalid type', <class 'google.cloud.firestore_v1.transforms.Sentinel'>)"
15:53:03,102 logger WARNING Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Arick', id=130414078, last_name='Vigas', type=<ChatType.PRIVATE>, username='ArickVigas'), date=datetime.datetime(2023, 2, 9, 13, 53, 2, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Arick', id=130414078, is_bot=False, is_premium=True, language_code='en', last_name='Vigas', username='ArickVigas'), group_chat_created=False, message_id=923, supergroup_chat_created=False, text='Хей'), update_id=441137235)" caused error "'DocumentSnapshot' object has no attribute 'update'"
15:54:34,953 logger WARNING Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Arick', id=130414078, last_name='Vigas', type=<ChatType.PRIVATE>, username='ArickVigas'), date=datetime.datetime(2023, 2, 9, 13, 54, 34, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Arick', id=130414078, is_bot=False, is_premium=True, language_code='en', last_name='Vigas', username='ArickVigas'), group_chat_created=False, message_id=924, supergroup_chat_created=False, text='Хей'), update_id=441137236)" caused error "('Cannot convert to a Firestore Value', Sentinel: Value used to set a document field to the server timestamp., 'Invalid type', <class 'google.cloud.firestore_v1.transforms.Sentinel'>)"
19:52:02,5 logger WARNING Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Arick', id=130414078, last_name='Vigas', type=<ChatType.PRIVATE>, username='ArickVigas'), date=datetime.datetime(2023, 2, 9, 17, 52, 1, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Arick', id=130414078, is_bot=False, is_premium=True, language_code='en', last_name='Vigas', username='ArickVigas'), group_chat_created=False, message_id=933, supergroup_chat_created=False, text='Привіт'), update_id=441137241)" caused error "can only concatenate str (not "coroutine") to str"
19:52:43,166 logger WARNING Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Arick', id=130414078, last_name='Vigas', type=<ChatType.PRIVATE>, username='ArickVigas'), date=datetime.datetime(2023, 2, 9, 17, 52, 42, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Arick', id=130414078, is_bot=False, is_premium=True, language_code='en', last_name='Vigas', username='ArickVigas'), group_chat_created=False, message_id=934, supergroup_chat_created=False, text='Привіт'), update_id=441137242)" caused error "'DocumentSnapshot' object is not subscriptable"
-----
19:54:57,617 logger WARNING Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Arick', id=130414078, last_name='Vigas', type=<ChatType.PRIVATE>, username='ArickVigas'), date=datetime.datetime(2023, 2, 9, 17, 54, 57, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Arick', id=130414078, is_bot=False, is_premium=True, language_code='en', last_name='Vigas', username='ArickVigas'), group_chat_created=False, message_id=935, supergroup_chat_created=False, text='Хей'), update_id=441137243)" caused error "'DocumentSnapshot' object is not subscriptable"
19:56:56,467 logger WARNING Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Arick', id=130414078, last_name='Vigas', type=<ChatType.PRIVATE>, username='ArickVigas'), date=datetime.datetime(2023, 2, 9, 17, 56, 55, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Arick', id=130414078, is_bot=False, is_premium=True, language_code='en', last_name='Vigas', username='ArickVigas'), group_chat_created=False, message_id=936, supergroup_chat_created=False, text='Hello'), update_id=441137244)" caused error "get() missing 1 required positional argument: 'field_path'"
19:58:03,512 logger WARNING Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Arick', id=130414078, last_name='Vigas', type=<ChatType.PRIVATE>, username='ArickVigas'), date=datetime.datetime(2023, 2, 9, 17, 57, 58, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='Arick', id=130414078, is_bot=False, is_premium=True, language_code='en', last_name='Vigas', username='ArickVigas'), group_chat_created=False, message_id=937, supergroup_chat_created=False, text='Hello'), update_id=441137245)" caused error "can only concatenate str (not "OpenAIObject") to str"
